export const paths = {
  index: "/",
  checkout: "/checkout",
  contact: "/contact",
  pricing: "/pricing",
  auth: {
    auth0: {
      callback: "/auth/auth0/callback",
      login: "/auth/auth0/login",
    },
    jwt: {
      login: "/auth/jwt/login",
      register: "/auth/jwt/register",
      forgotPassword: "/auth/jwt/password",
    },
    firebase: {
      login: "/auth/firebase/login",
      register: "/auth/firebase/register",
    },
    amplify: {
      confirmRegister: "/auth/amplify/confirm-register",
      forgotPassword: "/auth/amplify/forgot-password",
      login: "/auth/amplify/login",
      register: "/auth/amplify/register",
      resetPassword: "/auth/amplify/reset-password",
    },
  },
  authDemo: {
    forgotPassword: {
      classic: "/auth-demo/forgot-password/classic",
      modern: "/auth-demo/forgot-password/modern",
    },
    login: {
      classic: "/auth-demo/login/classic",
      modern: "/auth-demo/login/modern",
    },
    register: {
      classic: "/auth-demo/register/classic",
      modern: "/auth-demo/register/modern",
    },
    resetPassword: {
      classic: "/auth-demo/reset-password/classic",
      modern: "/auth-demo/reset-password/modern",
    },
    verifyCode: {
      classic: "/auth-demo/verify-code/classic",
      modern: "/auth-demo/verify-code/modern",
    },
  },
  dashboard: {
    index: "/dashboard",

    quotation: {
      index: "dashboard/quotation",
      buy: "/dashboard/quotation/buy",
      view: "/dashboard/quotation/:courseId",
      //invoice: '/dashboard/quotation/invoice',
      viewDetail: "/dashboard/quotation/viewDetail",
      edit: "/dashboard/quotation/edit",
      sell: "/dashboard/quotation/sell",
      service: "/dashboard/quotation/service",
      editService: "/dashboard/quotation/editService",
      editSales: "/dashboard/quotation/editSales",
    },
    account: "/dashboard/account",
    analytics: "/dashboard/analytics",
    blank: "/dashboard/blank",
    blog: {
      index: "/dashboard/blog",
      postDetails: "/dashboard/blog/:postId",
      postCreate: "/dashboard/blog/create",
    },
    purchaseorder: {
      index: "/dashboard/purchaseorder",
      create: "/dashboard/purchaseorder/",
      view: "/dashboard/purchaseorder/:customerId",
      viewDetail: "/dashboard/purchaseorder/viewDetail/:id",
      edit: "/dashboard/purchaseorder/edit",
      invoice: "/dashboard/purchaseorder/invoice",
    },
    services: {
      index: "/dashboard/services",

      createWorkorder: "/dashboard/services/workorder",
      workorderview: "/dashboard/services/workorderview",
      workorderDetail: "/dashboard/services/workorderDetail",
      workorderedit: "/dashboard/services/workorderedit",
      workorderdownload: "/dashboard/services/workorderdownload",

      createAMC: "/dashboard/services/amc",
      AMCview: "/dashboard/services/amcview",
      AMCDetail: "/dashboard/services/amcDetail",
      AMCedit: "/dashboard/services/amcedit",

      createTechnician: "/dashboard/services/technician",
      technicianview: "/dashboard/services/technicianview",
      technicianDetail: "/dashboard/services/technicianDetail",
    },

    application: {
      index: "/dashboard/application",
      tabCreate: "/dashboard/application/tab/create",
      tabView: "/dashboard/application/tab/view",
      tabDetail: "/dashboard/application/tab/detail",
      schemaCreate: "/dashboard/application/schema/create",
      schemaView: "/dashboard/application/schema/view",
      schemaDetail: "/dashboard/application/schema/detail",
      FieldCreate: "/dashboard/application/field/create",
      FieldView: "/dashboard/application/field/view",
      FieldDetail: "/dashboard/application/field/detail",
    },
    company: {
      index: "/dashboard/company",
      view: "/dashboard/company/view",
      viewDetail: "/dashboard/company/viewDetail",
      edit: "/dashboard/company/edit",
    },
    appUser: {
      index: "/dashboard/appUser",
      view: "/dashboard/appUser/view",
      edit: "/dashboard/appUser/edit",
      viewDetail: "/dashboard/appUser/viewDetail",
      createProfile: "/dashboard/appUser/profileCreate",
      viewProfile: "/dashboard/appUser/profileView",
    },

    ecommerce: "/dashboard/ecommerce",
    fileManager: "/dashboard/file-manager",
    invoices: {
      index: "/dashboard/invoices",
      details: "/dashboard/invoices/:orderId",
      viewDetail: "/dashboard/invoices/viewDetail",
    },
    jobs: {
      index: "/dashboard/jobs",
      create: "/dashboard/jobs/create",
      companies: {
        details: "/dashboard/jobs/companies/:companyId",
      },
    },
    kanban: "/dashboard/kanban",
    logistics: {
      index: "/dashboard/logistics",
      fleet: "/dashboard/logistics/fleet",
      viewDetail: "/dashboard/logistics/viewDetail",
      viewAllPo: "/dashboard/logistics/viewAllPo",
      viewAllSo: "/dashboard/logistics/viewAllSo",
      viewAllQo: "/dashboard/logistics/viewAllQo",
      viewAllWo: "/dashboard/logistics/viewAllWo",
      active: "/dashboard/logistics/active",
      inactive: "/dashboard/logistics/inactive",
      inactiveView: "/dashboard/logistics/inactiveView",
      activeView: "/dashboard/logistics/activeView",
      adminCreate: "/dashboard/logistics/adminCreate",
      adminView: "/dashboard/logistics/adminView",
      adminViewDetail: "/dashboard/logistics/adminViewDetail",
    },

    mail: "/dashboard/mail",
    orders: {
      index: "/dashboard/orders",
      invoice: "/dashboard/orders/:orderId",
      details: "/dashboard/orders/details",
      viewDetail: "/dashboard/orders/viewDetail/:id",
      edit: "/dashboard/orders/edit",
    },
    inventory: {
      index: "/dashboard/inventory",
      view: "/dashboard/inventory/view",
      edit: "/dashboard/inventory/edit",
      create: "/dashboard/inventory/create",
      viewDetail: "/dashboard/inventory/viewDetail/:id",
    },
    products: {
      index: "/dashboard/products",
      view: "/dashboard/products",
      create: "/dashboard/products/create",
      viewDetail: "/dashboard/products/viewDetail/:id",
    },
    social: {
      index: "/dashboard/social",
      profile: "/dashboard/social/profile",
      password: "/dashboard/social/password",
      feed: "/dashboard/social/feed",
    },
  },
  components: {
    index: "/components",
    dataDisplay: {
      detailLists: "/components/data-display/detail-lists",
      tables: "/components/data-display/tables",
      quickStats: "/components/data-display/quick-stats",
    },
    lists: {
      groupedLists: "/components/lists/grouped-lists",
      gridLists: "/components/lists/grid-lists",
    },
    forms: "/components/forms",
    modals: "/components/modals",
    charts: "/components/charts",
    buttons: "/components/buttons",
    typography: "/components/typography",
    colors: "/components/colors",
    inputs: "/components/inputs",
  },
  docs: "https://material-kit-pro-react-docs.devias.io",
  401: "/401",
  404: "/404",
  500: "/500",
};
